services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: books
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: ~
